### SITE SETTINGS ====

remote_theme: feeling-responsive
timezone: Europe/Amsterdam
title: "R blogtest"
author: mark # see authors.yml
site.description: "Test environment for showcasing R projects."
url: "https://mvdsman.github.io"
credits: '<p>Based on <a href="http://phlow.github.io/feeling-responsive/">Feeling Responsive</a> by <a href="http://phlow.de/">Phlow</a> with <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>.</p>'

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: "https://mvdsman.github.io/images/"

# Logo size is 600x80 pixels
logo: "logo.png"

# Gems
gems:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate


### PAGINATION ====

paginate: 5                      # Paginates all X entries
paginate_path: "blog/page:num"   # Pagination path › Important for blog page in /blog/ to work

# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
excerpt_separator: "<!--more-->"
include: ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md

# The language setting is used in /includes/header.html for html-settings
language: "en"


### DEFAULT SETTINGS ====

defaults:
  -
    scope:
      path: ""        # an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: false  # Hide metadata for all pages
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: mark     # Default author for pages
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      permalink: /:categories/:title/
      breadcrumb: true
      author: mark     # Default author for posts


### NAVIGATION ====
#  Open _data/navigation.yml to adjust the left and right topbar navigation


### FAVICON ====
favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'

### SASS ====

sass:
    sass_dir: _sass
    style: :compressed