### SITE SETTINGS ====

remote_theme: pages-themes/leap-day@v0.2.0
timezone: Europe/Amsterdam
title: "Digital Garden"
author: Mark van der Sman # see authors.yml
site.description: "Public collection of notes and learnings."
